# Generated by Django 2.1 on 2018-08-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_name', models.CharField(max_length=50)),
                ('appointment_phone', models.IntegerField()),
                ('appointment_date', models.DateField()),
                ('appointment_message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(blank=True, max_length=255)),
                ('banner_detail', models.TextField()),
                ('banner_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
