# Generated by Django 2.1 on 2018-08-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(db_column='title', max_length=255)),
                ('service_description', models.TextField(db_column='description')),
                ('service_image', models.ImageField(db_column='image', upload_to='banner/')),
            ],
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='banner_image',
            field=models.ImageField(upload_to='banner/'),
        ),
    ]
