# Generated by Django 2.1 on 2018-08-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_auto_20180830_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_name', models.CharField(max_length=25)),
                ('consultant_bio', models.CharField(max_length=50)),
                ('consultant_image', models.ImageField(upload_to='consultants/')),
            ],
        ),
    ]
