# Generated by Django 2.1 on 2018-08-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_consultantsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255)),
                ('blog_content', models.TextField()),
                ('blog_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CommmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_username', models.CharField(max_length=25)),
                ('comment_email', models.EmailField(max_length=254)),
                ('comment_text', models.TextField()),
            ],
        ),
    ]
