# Generated by Django 2.1 on 2018-08-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_blogmodel_commmentmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommmentModel',
            new_name='CommentModel',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='blog_comment',
            field=models.ManyToManyField(to='controller.CommentModel'),
        ),
    ]
