# Generated by Django 2.1 on 2018-08-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_auto_20180830_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_email',
            field=models.EmailField(db_column='Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_text',
            field=models.TextField(db_column='Comment'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_username',
            field=models.CharField(db_column='User Name', max_length=25),
        ),
    ]
